# Generated by Django 4.2.29 on 2026-03-09 02:25

from django.db import migrations, models
import django.db.models.deletion
import proposals.storage


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_grantcycle_score_weights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research Area',
                'verbose_name_plural': 'Research Areas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='proposal',
            name='application_template_file',
            field=models.FileField(blank=True, help_text='Research Grant Application Template (PDF/Word)', null=True, storage=proposals.storage.EncryptedFileStorage(), upload_to='proposals/templates/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_file',
            field=models.FileField(blank=True, help_text='Full research proposal (PDF)', null=True, storage=proposals.storage.EncryptedFileStorage(), upload_to='proposals/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='response_to_reviewers_file',
            field=models.FileField(blank=True, help_text='Optional response to reviewer comments', null=True, storage=proposals.storage.EncryptedFileStorage(), upload_to='proposals/responses/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='revised_proposal_file',
            field=models.FileField(blank=True, help_text='Revised proposal after Stage 1 review', null=True, storage=proposals.storage.EncryptedFileStorage(), upload_to='proposals/revisions/'),
        ),
        migrations.CreateModel(
            name='ProposalKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_keywords', to='proposals.keyword')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_keywords', to='proposals.proposal')),
            ],
            options={
                'verbose_name': 'Proposal Keyword',
                'verbose_name_plural': 'Proposal Keywords',
                'unique_together': {('proposal', 'keyword')},
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='proposals', through='proposals.ProposalKeyword', to='proposals.keyword'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='primary_research_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='proposals.researcharea'),
        ),
        migrations.CreateModel(
            name='ResearchAreaKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_area_mappings', to='proposals.keyword')),
                ('research_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_mappings', to='proposals.researcharea')),
            ],
            options={
                'verbose_name': 'Research Area Keyword Mapping',
                'verbose_name_plural': 'Research Area Keyword Mappings',
                'unique_together': {('research_area', 'keyword')},
            },
        ),
    ]
