# Generated by Django 4.2.29 on 2026-03-09 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0008_keyword_researcharea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the proposal record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who finalized the proposal submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_proposals', to=settings.AUTH_USER_MODEL),
        ),
    ]
