# Generated by Django 4.2.29 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_proposal_created_by_proposal_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantcycle',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional overall cycle end date', null=True),
        ),
        migrations.AlterField(
            model_name='grantcycle',
            name='start_date',
            field=models.DateField(blank=True, help_text='Optional overall cycle start date', null=True),
        ),
    ]
