# Generated by Django 4.2.29 on 2026-03-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_make_cycle_window_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaldecision',
            name='approved_grant_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final approved grant amount (required for acceptances)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='finaldecision',
            name='final_remarks',
            field=models.TextField(blank=True, default='', help_text='Final remarks from SRC Chair'),
        ),
    ]
