# Generated by Django 4.2.29 on 2026-03-25 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_alter_finaldecision_nullable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantcycle',
            name='max_reviewers_per_proposal',
            field=models.IntegerField(default=2, help_text='Maximum number of reviewers (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='grantcycle',
            name='revision_window_days',
            field=models.IntegerField(default=7, help_text='Number of days for revision after tentative acceptance', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_STAGE_1_REVIEW', 'Under Stage 1 Review'), ('STAGE_1_REJECTED', 'Stage 1 Rejected'), ('ACCEPTED_NO_CORRECTIONS', 'Accepted (No Corrections Required)'), ('TENTATIVELY_ACCEPTED', 'Tentatively Accepted'), ('REVISION_REQUESTED', 'Revision Requested'), ('REVISED_PROPOSAL_SUBMITTED', 'Revised Proposal Submitted'), ('REVISION_DEADLINE_MISSED', 'Revision Deadline Missed'), ('UNDER_STAGE_2_REVIEW', 'Under Stage 2 Review'), ('FINAL_ACCEPTED', 'Final Accepted'), ('FINAL_REJECTED', 'Final Rejected')], db_index=True, default='DRAFT', max_length=50),
        ),
    ]
