# Generated by Django 4.2.29 on 2026-03-30 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0012_alter_grantcycle_max_reviewers_per_proposal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=500)),
                ('use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('from_name', models.CharField(blank=True, default='CTRG Grant System', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Configuration',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('notification_type', models.CharField(max_length=100)),
                ('trigger_event', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='proposals.proposal')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='proposals_n_sent_at_c54209_idx'), models.Index(fields=['status'], name='proposals_n_status_342f04_idx'), models.Index(fields=['notification_type'], name='proposals_n_notific_8cac21_idx')],
            },
        ),
    ]
