"""
Django settings for CTRG Grant System

This settings file uses environment variables for configuration.
Environment variables are loaded from the .env file via django-environ.

For local development, copy .env.example to .env and update values.
For production, set environment variables directly on the server.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see:
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from celery.schedules import crontab
import environ

# ========================================
# Build Paths and Environment Setup
# ========================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
RUNNING_TESTS = 'test' in sys.argv

# Initialize environment variable reader
env = environ.Env(
    # Set default values and casting for environment variables
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    SECRET_KEY=(str, 'django-insecure-default-key-please-change'),
    DATABASE_ENGINE=(str, 'django.db.backends.postgresql'),
    DATABASE_NAME=(str, 'ctrg_grant_db'),
    DATABASE_USER=(str, ''),
    DATABASE_PASSWORD=(str, ''),
    DATABASE_HOST=(str, 'localhost'),
    DATABASE_PORT=(str, '5432'),
    EMAIL_BACKEND=(str, 'django.core.mail.backends.console.EmailBackend'),
    CORS_ALLOW_CREDENTIALS=(bool, True),
    USE_X_FORWARDED_HOST=(bool, False),
    SECURE_PROXY_SSL_HEADER_ENABLED=(bool, False),
    CACHE_BACKEND=(str, 'locmemcache'),
)

# Read .env file if it exists
env_file = os.path.join(BASE_DIR, '.env')
if os.path.exists(env_file):
    environ.Env.read_env(env_file)

# ========================================
# Core Django Settings
# ========================================

# SECURITY WARNING: keep the secret key used in production secret!
# In production, generate a new key: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = env('SECRET_KEY')

# Reject startup with the insecure placeholder key when not in DEBUG mode.
_INSECURE_KEY_PREFIX = 'django-insecure-'
if not env('DEBUG') and SECRET_KEY.startswith(_INSECURE_KEY_PREFIX):
    raise ImproperlyConfigured(
        "SECRET_KEY must be changed from the insecure default before running in production. "
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# Hosts allowed to access the application
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

# ========================================
# Application Definition
# ========================================

INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',  # Token-based authentication
    'corsheaders',

    # Local apps
    'users',
    'proposals',
    'reviews',
]

MIDDLEWARE = [
    # CORS middleware must be at the top
    'corsheaders.middleware.CorsMiddleware',

    # Django core middleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # GZipMiddleware removed: vulnerable to BREACH attacks over HTTPS.
    # Use reverse proxy (nginx/cloudfront) gzip instead.
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ========================================
# Database Configuration
# ========================================
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Force SQLite during test runs so local/CI tests do not require a PostgreSQL driver.
if RUNNING_TESTS:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'test_db.sqlite3',
        }
    }
# PostgreSQL is the default/original database (production-first setup).
# SQLite is only used if explicitly configured.
elif env('DATABASE_ENGINE') == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': env('DATABASE_ENGINE'),
            'NAME': BASE_DIR / env('DATABASE_NAME'),
        }
    }
# PostgreSQL with connection pooling
else:
    DATABASES = {
        'default': {
            'ENGINE': env('DATABASE_ENGINE'),
            'NAME': env('DATABASE_NAME'),
            'USER': env('DATABASE_USER'),
            'PASSWORD': env('DATABASE_PASSWORD'),
            'HOST': env('DATABASE_HOST'),
            'PORT': env('DATABASE_PORT'),
            # Connection pooling for better performance
            'CONN_MAX_AGE': 0,  # 0 for serverless (new connection per request)
            'OPTIONS': {
                'connect_timeout': 10,
                'options': '-c statement_timeout=30000',  # 30 second query timeout
                'sslmode': env('DATABASE_SSLMODE', default='require'),
            },
        }
    }

# ========================================
# Password Validation
# ========================================
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Require minimum 8 characters
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ========================================
# Internationalization
# ========================================
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = env('LANGUAGE_CODE', default='en-us')
TIME_ZONE = env('TIME_ZONE', default='UTC')
USE_I18N = True
USE_TZ = True

# ========================================
# Static Files (CSS, JavaScript, Images)
# ========================================
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ========================================
# Media Files (User Uploads)
# ========================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload size limits (in bytes) - minimum 50MB per requirements
FILE_UPLOAD_MAX_MEMORY_SIZE = env.int('FILE_UPLOAD_MAX_MEMORY_SIZE', default=52428800)  # 50MB
DATA_UPLOAD_MAX_MEMORY_SIZE = env.int('DATA_UPLOAD_MAX_MEMORY_SIZE', default=52428800)  # 50MB

# File encryption at rest
# Generate a key with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# When not set, files are stored unencrypted (development fallback).
FILE_ENCRYPTION_KEY = env('FILE_ENCRYPTION_KEY', default='')
if not DEBUG and not FILE_ENCRYPTION_KEY:
    raise ImproperlyConfigured('FILE_ENCRYPTION_KEY must be set when DEBUG=False.')

# ========================================
# Cache Configuration
# ========================================

CACHE_BACKEND = env('CACHE_BACKEND').strip().lower()
if CACHE_BACKEND == 'redis':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': env('CACHE_LOCATION', default='redis://127.0.0.1:6379/1'),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'ctrg-default',
        }
    }

# ========================================
# Authentication Configuration
# ========================================

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Default auto field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========================================
# REST Framework Configuration
# ========================================
# Token-based authentication for API security

REST_FRAMEWORK = {
    # Authentication classes
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Primary: Token auth for API
        'rest_framework.authentication.SessionAuthentication',  # Secondary: For Django admin
    ],

    # Permission classes
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Require authentication by default
    ],

    # Pagination - prevents performance issues with large datasets
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,  # Default page size

    # Renderer classes
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # Disable in production if needed
    ],

    # Parser classes
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],

    # Error handling
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',

    # Date/time formatting
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',

    # Throttling (Rate Limiting)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',      # Anonymous users: 100 requests per hour
        'user': '1000/hour',     # Authenticated users: 1000 requests per hour
        'login': '5/minute',     # Login endpoint: 5 attempts per minute (brute force protection)
        'upload': '20/hour',     # File uploads: 20 per hour
        'registration': '10/hour',  # Registration/invitation validation: 10 per hour per IP
    },
}

if not DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = [
        'rest_framework.renderers.JSONRenderer',
    ]

# ========================================
# CORS Configuration
# ========================================
# Cross-Origin Resource Sharing settings for frontend access

# Allowed origins (frontend URLs)
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://192.168.0.101:5173',
])

# In production the regex list must be empty or replaced with explicit origins.
# The LAN subnet regex is only safe for local development; it would allow any
# host on a 192.168.x.x/16 network to bypass CORS in a production deployment.
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
        r"^http://192\.168\.\d{1,3}\.\d{1,3}:\d+$",
    ]
else:
    # In production, rely solely on CORS_ALLOWED_ORIGINS (explicit list).
    CORS_ALLOWED_ORIGIN_REGEXES = []

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# Frontend URL for building invitation links, email links, etc.
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173')

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = env('CORS_ALLOW_CREDENTIALS')

# Allowed methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allowed headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-retry-count',  # Allow retry header from frontend
]

# ========================================
# Email Configuration
# ========================================

EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST', default='localhost')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@nsu.edu')

# Email timeout (seconds)
EMAIL_TIMEOUT = 10

# ========================================
# Celery Configuration (Background Tasks)
# ========================================

# Broker URL (Redis)
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')

# Celery settings
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# Celery Beat Schedule (Periodic Tasks)
CELERY_BEAT_SCHEDULE = {
    # Check for revision deadline violations every hour
    'check-revision-deadlines': {
        'task': 'proposals.tasks.check_revision_deadlines',
        'schedule': crontab(hour='*/1'),  # Every hour
    },

    # Send revision deadline reminders (24 hours before)
    'send-revision-reminders': {
        'task': 'proposals.tasks.send_deadline_reminders',
        'schedule': crontab(hour='9', minute='0'),  # Daily at 9 AM
    },

    # Send review deadline reminders (48 hours before)
    'send-review-reminders': {
        'task': 'proposals.tasks.send_review_reminders',
        'schedule': crontab(hour='9', minute='0'),  # Daily at 9 AM
    },
}

# ========================================
# Security Settings
# ========================================

# Security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = env('SECURE_REFERRER_POLICY', default='same-origin')
SECURE_CROSS_ORIGIN_OPENER_POLICY = env('SECURE_CROSS_ORIGIN_OPENER_POLICY', default='same-origin')
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if env.bool('SECURE_PROXY_SSL_HEADER_ENABLED') else None
USE_X_FORWARDED_HOST = env.bool('USE_X_FORWARDED_HOST', default=False)

# HTTPS/SSL settings (production only)
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = env('SESSION_COOKIE_NAME', default='ctrg_sessionid')

# CSRF settings
CSRF_COOKIE_HTTPONLY = True  # Prevent JS access to CSRF cookie; frontend reads token from response header
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = env('CSRF_COOKIE_NAME', default='ctrg_csrftoken')

if not DEBUG:
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=True)
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True)
    SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=True)

# ========================================
# Logging Configuration
# ========================================

# Create logs directory if it doesn't exist.
# Fall back to /tmp on read-only filesystems (e.g. Vercel serverless) —
# mkdir(exist_ok=True) succeeds even on read-only dirs, so we must also
# verify write access by attempting to create a temp file.
_logs_default = BASE_DIR / 'logs'
try:
    _logs_default.mkdir(exist_ok=True)
    _test = _logs_default / '.write_test'
    _test.touch()
    _test.unlink()
    LOGS_DIR = _logs_default
except (PermissionError, OSError):
    LOGS_DIR = Path('/tmp/ctrg-logs')
    LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # Log formatters
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    # Log handlers
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },

    # Root logger
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO' if not DEBUG else 'DEBUG',
    },

    # Django loggers
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Application loggers
        'proposals': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'reviews': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# ========================================
# Development vs Production Settings
# ========================================

# In production, consider:
# - DEBUG = False
# - ALLOWED_HOSTS = ['yourdomain.com']
# - Use PostgreSQL database
# - Use Redis for Celery
# - SECURE_SSL_REDIRECT = True
# - SESSION_COOKIE_SECURE = True
# - CSRF_COOKIE_SECURE = True
# - Use environment variables for all secrets
# - Use WhiteNoise or cloud storage for static files
# - Set up proper logging and monitoring
