# Generated by Django 4.2.28 on 2026-03-02 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0008_reviewerprofile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='chair_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='chair_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_review_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='chair_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='review_validity',
            field=models.CharField(choices=[('INCLUDED', 'Included in Decision'), ('REJECTED', 'Rejected by SRC Chair')], default='INCLUDED', help_text='Whether the submitted review is included in chair decisions', max_length=20),
        ),
    ]
