# Generated by Django 4.2.29 on 2026-03-09 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0009_proposal_created_by_proposal_submitted_by'),
        ('reviews', '0009_reviewassignment_chair_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage2review',
            name='is_chair_review',
            field=models.BooleanField(default=False, help_text='True when the Stage 2 review is authored directly by the SRC Chair.'),
        ),
        migrations.AddField(
            model_name='stage2review',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='Proposal under Stage 2 review. Required for direct SRC Chair reviews.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage2_reviews', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='stage2review',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Reviewer or SRC Chair who authored this Stage 2 review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage2_reviews_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stage2review',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage2_review', to='reviews.reviewassignment'),
        ),
    ]
