# Generated by Django 4.2.29 on 2026-03-23 16:13

import django.core.validators
from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_stage2review_is_chair_review_stage2review_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerprofile',
            name='cv',
            field=models.FileField(blank=True, help_text='Optional reviewer CV for SRC Chair review (PDF/DOC/DOCX, max 5 MB)', null=True, upload_to='reviewer_cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), reviews.models._validate_cv_size]),
        ),
    ]
