# Generated by Django 4.2.29 on 2026-03-25 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_reviewerprofile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage1score',
            name='budget_appropriateness_score',
            field=models.IntegerField(default=0, help_text='Appropriateness of the proposed budget (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='stage1score',
            name='clarity_score',
            field=models.IntegerField(default=0, help_text='Clarity and rationality of the research question, thesis, hypotheses (0-15)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='stage1score',
            name='impact_score',
            field=models.IntegerField(default=0, help_text='Potential impact of research findings/Policy implication/Contribution to existing knowledge (0-15)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='stage1score',
            name='literature_review_score',
            field=models.IntegerField(default=0, help_text='Literature review (assessment of relevant background materials and prior related studies) (0-15)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='stage1score',
            name='methodology_score',
            field=models.IntegerField(default=0, help_text='Appropriateness of the methodology (0-15)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='stage1score',
            name='originality_score',
            field=models.IntegerField(default=0, help_text='Originality of the proposed research (0-15)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='stage1score',
            name='publication_potential_score',
            field=models.IntegerField(default=0, help_text='Potential for publication/dissemination of research results (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='stage1score',
            name='timeline_practicality_score',
            field=models.IntegerField(default=0, help_text='Practicality of the proposed time frame (0-5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='stage2review',
            name='revised_score',
            field=models.IntegerField(blank=True, help_text='Optional revised score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
